### ISSUE TITLE
Allow the recording of hover or mouse activities

### ISSUE THREAD

**Issue by adamchenwei** [checkly/headless-recorder#55]
seems the mouse movement are not recorded. so therefore, the hover triggered dom won't be able to get triggered... is there way to enable that recording, or its something can not be done with puppeteer as a hard limit? 

really like the tool able to pick up the dom correctly, way better than my guessing game. ha.
keep it up!

**Comment by tnolet** [comment]
Hi @adamchenwei this is not a bug. It is just not implemented as a feature. Please remove the [bug] from the title and rewrite your question as a feature request. 

Even better, add the feature as a pull request and check our [contribution guidelines](https://github.com/checkly/puppeteer-recorder/blob/master/CONTRIBUTING.md)

**Comment by adamchenwei** [comment]
@tnolet by `not implemented as a feature` meaning`, puppeteer is able to track mouse and hover actions just need to be added to this plugin? thanks!

**Comment by tnolet** [comment]
@adamchenwei I'm not sure. We can do things with coordinates and mouse actions, that is sure. The exact details will have to be prototyped and researched.

**Comment by choleaoum** [comment]
definitely looking forward to this feature, tracking mouse movements and actions would be a wonderful idea.

**Comment by saranshbarua** [comment]
@tnolet @choleaoum a few days ago I was tinkering with the extension just because I needed to track the mouse movements to get the coordinates of the cursor and it is possible (ss). My only concern is that people don't need this feature always. We can add a button to toggle the mousemove behavior but I'm not sure if all of this goes with the contribution guidelines: `Features should serve the general public. Very specific things for your use case are frowned upon.`

![Screenshot 2019-07-15 at 4 53 31 PM](https://user-images.githubusercontent.com/23500643/61213496-d40f2600-a722-11e9-8a5b-7e99c567b66e.png)

**Comment by ephetic** [comment]
Do people need to track movement or just the state after the mouse is in the desired location (e.g. to generate at wait selector)?  Would a hotkey to insert a wait or exist for the currently hovered item work?

**Comment by saranshbarua** [comment]
My personal use case was to track the movement of the mouse while drawing on canvas, so I wanted the exact mouse coordinates to replicate the drawing mechanism. But there can be other uses as well. For eg, while using a slider (like the one in shopping sites to add filters)

**Comment by saranshbarua** [comment]
@tnolet do you want me to submit a PR for this? What are your thoughts?

**Comment by ephetic** [comment]
@saranshbarua How many mouse events does this typically log for you?  Puppeteer supports mouse movement [interpolation](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-mousemovex-y-options), so it'd be cool if there were a way to merge approximately collinear movements (but then you'd need a threshold control in the recorder settings too and maybe away to fake timing and on and on).

**Comment by tnolet** [comment]
@saranshbarua that would be great! 

Two concerns:

1. I guess a challenge would be the toggling on / off of this feature. From a user perspective, it would be best to not always record mouse moves as it will flood the recording. So we should either introduce a keyboard switch or some other user toggle. A user should be able to toggle this during a recording.

2. The mouse movements probably need to be "diluted" or debounced as it can otherwise generate way too much data.

Please take into account the following:

- There should be a test / some test to cover this new behaviour
- please take care to look at the code conventions.

**Comment by Pain-and-Love** [comment]
it seems Recorder can't record the scroll event...

**Comment by tnolet** [comment]
@adamchenwei we are picking up development again, please have a look at https://github.com/checkly/puppeteer-recorder/issues/83

**Comment by segments-tobias** [comment]
Any updates on this? I'm dealing with the same scenario (recording canvas events), and this would greatly speed up my workflow!

**Comment by smith558** [comment]
Interested!

**Comment by smith558** [comment]
> @tnolet @choleaoum a few days ago I was tinkering with the extension just because I needed to track the mouse movements to get the coordinates of the cursor and it is possible (ss). My only concern is that people don't need this feature always. We can add a button to toggle the mousemove behavior but I'm not sure if all of this goes with the contribution guidelines: `Features should serve the general public. Very specific things for your use case are frowned upon.`
> 
> ![Screenshot 2019-07-15 at 4 53 31 PM](https://user-images.githubusercontent.com/23500643/61213496-d40f2600-a722-11e9-8a5b-7e99c567b66e.png)

Any chance you've made a fork available? I'd be quite interested in this. :)

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
